[package]
name = "rapl-interface"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
sysinfo = "0.33.1"

[dependencies]
csv = "1.3.1"
once_cell = "1.20.3"
serde = { version = "1.0.218", features = ["derive"] }
thiserror = "2.0.11"
