[package]
name = "pidigits"
version = "0.1.0"
edition = "2021"

[dependencies]
rapl-lib = { path = "../rapl-interface/rapl-lib" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
target-cpu = "core2"
