[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.16.0"
rapl-lib = { path = "../../../lib/rapl-interface/rapl-lib" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
target-cpu = "native"
